### ISSUE TITLE
USER STORY: Find a running group

### ISSUE THREAD

**Issue by jonnlai** [jonnlai/Love-Running-Project#3]
In order to **find other people to run with** as a **runner**, I can **find and join a local running group**

## Acceptance criteria:

- The page contains information about local groups
- The page allows the user to add their details to join a group

## Tasks:

- [ ] Display all the running groups
- [ ] Create a joining form
- [ ] Create HMTL and CSS code to style the page
